FROM python:3-alpine

WORKDIR /usr/src/ehead

COPY requirements.txt ./
RUN apk add --no-cache gcc musl-dev && \
    pip install --no-cache-dir -r requirements.txt

COPY ehead/ .

EXPOSE 8080

ENTRYPOINT ["python", "/usr/src/ehead/server.py", "-b", "0.0.0.0"]
